extends:
  - plugin:vue/vue3-recommended
  - plugin:prettier/recommended
  - '@vue/typescript'
parser: vue-eslint-parser
parserOptions:
  parser: '@typescript-eslint/parser'
  sourceType: module
ignorePatterns:
  - gwt-old
  - dist
  - dist.local
