branches:
- main
plugins:
- '@semantic-release/commit-analyzer'
- '@semantic-release/release-notes-generator'
- - '@semantic-release/exec'
  # Get next version info to file to be used in build.
  # It's a trick: first do `semantic-release --dry-run` to get the
  # version number, then build (uses .version.local) and finally release.
  # See: https://github.com/semantic-release/semantic-release/issues/1647#issuecomment-707934082
  - verifyReleaseCmd: echo "${nextRelease.version}" > .version.local
- '@semantic-release/changelog'
- - '@semantic-release/npm'
  # We don't need NPM. Releasing the build to Github is enough.
  - npmPublish: false
- - '@semantic-release/git'
  - assets:
    - package.json
    - CHANGELOG.md
    message: |-
      chore(release): ${nextRelease.version} [skip ci]

      ${nextRelease.notes}
- - '@semantic-release/github'
  - assets:
    - 'release.local/*'
