branches:
- main
plugins:
- '@semantic-release/commit-analyzer'
- '@semantic-release/release-notes-generator'
- '@semantic-release/changelog'
- - '@semantic-release/npm'
  - npmPublish: false
- - '@semantic-release/git'
  - assets:
    - package.json
    - CHANGELOG.md
    message: |-
      chore(release): ${nextRelease.version} [skip ci]

      ${nextRelease.notes}
- - '@semantic-release/github'
  - assets:
    - 'dist/**'
- - '@semantic-release/exec'
  # Get next version info to file to be used in build
  # See: https://github.com/semantic-release/semantic-release/issues/1647#issuecomment-707934082
  - verifyConditionsCmd: 'echo ${nextRelease.version} >> .version.local'
