name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install
      - name: Get release version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        # semantic-release:dry-run generates .version.local file
        # See: .releaserc.yaml
        run: pnpm run semantic-release:dry-run
      - name: Make sure .version.local exists
        run: |
          ls -la
          test -f .version.local
          cat .version.local
      - name: Build
        run: |
          echo "APP_VERSION=$(cat .version.local)" >> .env.production.local
          echo "APP_LINK=${{ github.server_url }}/${{ github.repository }}/releases/tag/$(cat .version.local)" >> .env.production.local
          pnpm run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: pnpm run semantic-release
